name: Game Database Browser Release (Windows x64)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/GameDatabaseBrowser/GameDatabaseBrowser.csproj 
    - name: Build
      run: dotnet build ./src/GameDatabaseBrowser/GameDatabaseBrowser.csproj --no-restore --configuration Release
    - name: Get current date
      run: echo "DATE=$(date +'%Y%m%d')" >> $env:GITHUB_ENV
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GameDatabaseBrowser-nightly-${{ env.DATE }}-Release-windows-x64
        path: |
          ./src/GameDatabaseBrowser/bin/x64/Release/net6.0
          !./src/GameDatabaseBrowser/bin/x64/Release/net6.0/*.pdb
          !./src/GameDatabaseBrowser/bin/x64/Release/net6.0/*.xml
